---
version: "3"
services:
  postgres:
    image: docker.io/library/postgres:14.3-alpine
    environment:
      - POSTGRES_DB=mlflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: docker.io/bitnami/minio:2023.6.23
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=my-mlflow
    volumes:
      - miniodata:/data
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-registry/huang06/mlflow:latest
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_DEFAULT_REGION=ap-northeast-1
    entrypoint:
      - /bin/bash
      - -c
    command:
      - mlflow server --backend-store-uri "postgresql+psycopg2://postgres:postgres@postgres:5432/mlflow" --artifacts-destination "s3://my-mlflow" --host 0.0.0.0 --port 5000
volumes:
  pgdata:
  miniodata:
