---
version: "3"
services:
  db:
    image: docker.io/library/postgres:14.3-alpine
    environment:
      - POSTGRES_DB=mlflow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    # user: "${UID}:${GID}"
    volumes:
      # - ./data/pgdata:/var/lib/postgresql/data
      # - /etc/passwd:/etc/passwd:ro
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  minio:
    image: docker.io/bitnami/minio:2023.6.23
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=my-mlflow
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata:
